### ISSUE TITLE
Add support for Daisuki

### ISSUE THREAD

**Issue by fb39ca4** [LHCGreg/animerecs#2]
Streaming selection is still small, but it is a good option for the shows it does have.

**Comment by LHCGreg** [comment]
Thanks for your interest. I agree having Daisuki support would be nice. Unfortunately I am occupied with other projects lately and will not be able to implement it soon.

**Comment by rivnam** [comment]
anything I can do to help? adding more international services would be ace

**Comment by LHCGreg** [comment]
@rivnam I actually added support for Viewster recently (not deployed yet) and plan on adding Daisuke and maybe Netflix soon when I get a chance. If you would like to help add support for other services, https://github.com/LHCGreg/animerecs/commit/d41e1267401eb23fdbab19230f413f486136d472 is an example of what is needed:

- Add a SQL script adding the service to the streaming_service table.
- Add it to the StreamingService enum with the ID used in the SQL script.
- Write a class in the AnimeRecs.UpdateStreams project that implements the IAnimeStreamInfoSource interface. HtmlParsingAnimeStreamInfoSource and HtmlRegexAnimeStreamInfoSource are base classes that simplify it when you just need to get one page's html and extract the available streams from it. Other cases will require custom code - for example, Crunchyroll requires you to log in before it will list "mature content" streams and Hulu and Viewster require getting some kind of API token and paging through query results until no more are returned.
- Modify GetStreamInfoSources() in AnimeRecs.UpdateStreams.Program to return an instance of that new class.
- Add an icon to Content/ in AnimeRecs.Web. I do this by getting the website's favicon and using IcoFX to export to PNG then running a PNG minifier on it to reduce the file size.
- Modify AnimeRecs.Web/HtmlHelpers.cs to handle the new service.

**Comment by LHCGreg** [comment]
Daisuki support is now live!
