### ISSUE TITLE
Add support for Viewster?

### ISSUE THREAD

**Issue by tjl** [LHCGreg/animerecs#3]
I noticed that in addition to Daisuki, there's no support for Viewster either. In it's anime collection there's some that aren't listed elsewhere in your list, like Bokura ga Ita and Strawberry Panic.

**Comment by LHCGreg** [comment]
I just started watching Kuuchuu Buranko on Viewster. Stay tuned in the next couple days.

**Comment by LHCGreg** [comment]
Viewster support has been added.
